### ISSUE TITLE
逻辑优化

### ISSUE THREAD

**Issue by Jursin** [hello8693DSZ/dsz-exam-showboard#14]
- 开考15分钟前开始改为显示倒计时
- 考试进行中时显示倒计时，并全屏居中，隐藏考试列表
- 考试结束前15分钟醒目提醒
- 考试结束后重新显示考试列表

**Comment by MKStoler4096** [comment]
> 考试结束前15分钟提醒

原来有但是不够醒目

> 考试进行中时显示倒计时，并全屏居中，隐藏考试列表
> 考试结束后重新显示考试列表

别啊，我刚改完就撤下来(っ °Д °;)っ

> 开考15分钟前开始改为显示倒计时

同求，自己没那个实力写

**Comment by MKStoler4096** [comment]
> 开考15分钟前开始改为显示倒计时

基本实现了……但是没法确定刷新时间？

（见我的fork）

**Comment by MKStoler4096** [comment]
@Jursin 你如果方便的话能把你的pr和issue在我那里再发一遍呗（）

**Comment by Jursin** [comment]
> @Jursin 你如果方便的话能把你的pr和issue在我那里再发一遍呗（）

好的
