### ISSUE TITLE
换掉 Electron 自带的图标

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [hello8693DSZ/dsz-exam-showboard#3]
我找 Bing 画了一下，然后自己改了改（）
~~（大体上还行？）~~
![icon](https://github.com/user-attachments/assets/ee99abd3-2c21-419e-8361-fccf3837899c)
主要是看起来全是一个样，还容易和ecs混了（）

**Comment by Qsgz2023ji5ban** [comment]
还有就是编译的 Win x64 版本我扔这里了：
https://github.com/Qsgz2023ji5ban/dsz-exam-showboard/releases/tag/0.1.0

**Comment by hello8693DSZ** [comment]
我尽快把本地windows vm配好，感谢您的贡献🌹🌹🌹

**Comment by Qsgz2023ji5ban** [comment]
OK
顺便询问一下这个图标如何？

**Comment by hello8693DSZ** [comment]
的确跟软件内容无关（）而且这个图标不太符合Material Design风格。

**Comment by Qsgz2023ji5ban** [comment]
看见群里有logo了，这个工单我就关了（）
