### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Jursin** [hello8693DSZ/dsz-exam-showboard#6]
1. 右侧考试列表的考试状态到点无法自动更新
2. 右上角关闭按钮旁的时间无法自动更新

**Comment by Jursin** [comment]
![2024-09-08_21-54-32](https://github.com/user-attachments/assets/0c277749-71ca-4634-8566-18d423753f55)
这是后来截的，当时左边状态正常，但右边的状态没有自动更新，右上角时间也是

**Comment by hello8693DSZ** [comment]
我刚想发issue（）

我的锅，的确没做自动更新，后面版本修复。最近有点忙。感谢您的反馈

**Comment by MKStoler4096** [comment]
#11 已修复

**Comment by MKStoler4096** [comment]
@Jursin 已修复并合并，阁下可自行关闭此issue
